# Generated by Django 4.2.14 on 2024-07-28 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderitemhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='placed_at',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='placed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='OrderItemHistory',
        ),
    ]
